#!/usr/bin/env bash

# Check if this is the initial commit
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Use git diff-index to check for whitespace errors
if ! git diff-index --check --cached $against
then
    echo "Aborting commit due to whitespace errors."
    exit 1
else
    # Fail on first line that fails.
    set -e

    NEW_FILES=$(git --no-pager diff --name-only --cached)
    PY_FILES=$(echo "$NEW_FILES" | { grep .py || true; })

    if [ -n "$PY_FILES" ];
    then
        make test_ci
        exit 0
    fi
    exit 0
fi
