from typing import Any

class BeautifulSoup:
    def __init__(self, markup: str, features: str) -> None: ...
    def prettify(self) -> str: ...
    def new_tag(self, type_: str, **attr: Any) -> Any: ...
